INSERT INTO accounts_by_user (username, account_number, cash_balance, name) VALUES ('leo', '8902831', 200.12, 'Leobardo Ruiz');
INSERT INTO accounts_by_user (username, account_number, cash_balance, name) VALUES ('vale', '4267464', 30039.3, 'Valeria');
INSERT INTO accounts_by_user (username, account_number, cash_balance, name) VALUES ('leo', '3472698', 9731.2, 'Leobado Ruiz');
INSERT INTO accounts_by_user (username, account_number, cash_balance, name) VALUES ('ariel', '5309837', 18099.87, 'Ariel');
INSERT INTO accounts_by_user (username, account_number, cash_balance, name) VALUES ('tomasa', '1378058', 5438.1, 'La Tomasa');
INSERT INTO accounts_by_user (username, account_number, cash_balance, name) VALUES ('chunior', '9873653', 12.9, 'El Chunior');
INSERT INTO accounts_by_user (username, account_number, cash_balance, name) VALUES ('ariel', '8912161', 654.3, 'Ariel');
